from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Mensajes(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(302, 252)
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setStyleSheet("background-color: rgb(242, 242, 242);\n""\n""\n""\n""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 302, 251))
        self.frame.setStyleSheet("border: 3px solid;\n""border-color: rgb(232, 137, 137);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 30, 275, 131))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:  rgb(232, 137, 137);\n""border: None\n""")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(9, 10, 281, 31))
        self.frame_2.setStyleSheet("background-color: rgb(242, 242, 242);\n""border: 0px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.btnClose = QtWidgets.QPushButton(self.frame_2)
        self.btnClose.setGeometry(QtCore.QRect(260, 1, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.btnClose.setFont(font)
        self.btnClose.setStyleSheet("QPushButton{\n""    background-color: rgb(242, 242, 242);\n""    border: None;\n""    color: rgb(232, 137, 137);\n""}\n""QPushButton:hover{\n""    \n""    color: rgb(232, 100, 100);\n""}")
        self.btnClose.setObjectName("btnClose")
        self.btnAceptar = QtWidgets.QPushButton(self.frame)
        self.btnAceptar.setGeometry(QtCore.QRect(100, 160, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAceptar.setStyleSheet("QPushButton {\n""    border: 2px solid;\n""    color:#e88989;\n""    border-color: #e88989;\n""    border-radius: 20px;\n""\n""}\n""QPushButton:hover {\n""    background-color: #e88989;\n""    color: \'#ffffff\'\n""\n""\n""}")
        self.btnAceptar.setObjectName("btnAceptar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnClose.setText(_translate("MainWindow", "X"))
        self.btnAceptar.setText(_translate("MainWindow", "ACEPTAR"))
     

